### ISSUE TITLE
Error in joomla 4

### ISSUE THREAD

**Issue by mefistofelos** [svanschu/SchuWeb-Sitemap#107]
**Steps to reproduce**
Install to joomla 4, go to component view, click on sitemap that's already in there. As a matter of fact, all links show errors, "new", "edit" as well.

clicking on "new", "edit", I get: 0 Typed property SchuWeb_SitemapViewSitemap::$form must be an instance of mixed, Joomla\CMS\Form\Form used

Clicking on Sitemap: Typed Property SchuWeb_SitemapXmlDisplayer::$DefaultLanguage Must Be An Instance Of Mixed, String Used

**System information**
Joomla version: 4.2.7
SchuWeb-Sitemap version: 4
PHP version: 7.4.33
DB: 10.3.38-MariaDB

**Comment by svanschu** [comment]
Hi,
sorry to say that, but that's sadly a known issue with the PHP 7.4.33 version. :( You can read more about in the forum.
https://extensions.schultschik.com/community-forum/schuweb-sitemap/119-typed-property-schuweb_sitemapviewsitemap-$form-must-be-an-instance-of-mixed,?start=0

Do you have a chance to use another PHP version? I currently rework the whole extension for J4, but it will take some more time.

**Comment by mefistofelos** [comment]
Hi
I think I saw somewhere that it should work with this version of PHP - that's why I've opened a ticket.
I didn`t test it with php 8 though, I believe it works.
Thanks!

**Comment by svanschu** [comment]
Yes your right, I had a 7.4 environment running, but never had those issues. Somewhere in the pipeline I made a mistake and lost the compatibility.
I would like to focus on the next version with redesign and min php8 to get it fast ready, so people can use that one in the future.
