### ISSUE TITLE
DPCalendar plugin

### ISSUE THREAD

**Issue by AlainRnet** [svanschu/SchuWeb-Sitemap#108]
I install the SchuWeb Sitemap Integration for DPCalendar plugin and activate it. I try several options but no event displays on the sitemap.
I created an item menu for schuweb_sitemap but no event displays on the sitemap.
I activate debug mode but I cannot wee anything about this issue.

The menu item is a DPCalendar List : https://www.estimame.com/index.php?option=com_schuweb_sitemap&view=html&tmpl=component&id=1
What am I doing wrong ?

**System information**
Joomla version: 4.4.0
SchuWeb-Sitemap version: 4.0.0
PHP version: 8.1.25
Database version:10.6.14-MariaDB

**Comment by AlainRnet** [comment]
OK, I see that only calendar view or single event displays events in sitemap.
But XML seem wrong : https://www.estimame.com/index.php?option=com_schuweb_sitemap&view=xml&tmpl=component&id=1

**Comment by svanschu** [comment]
Hi, thx for report.

I'm currently on a business trip. I will look into it and test again when I'm back.

Best regards

**Comment by AlainRnet** [comment]
Thank you very much. I don't see here in the code the sitemap DPCalendar plugin. Here is the code I added to dpcalendar.php, on line 54 :
`
            case 'list':
                if ($id) {
                    $node->uid = 'com_dpcalendar' . $id;
                } else {
                    $node->uid = 'com_dpcalendar';
                }
                $node->expandible = true;
                break;`
and on line 132 :
`            case 'list':
                if ($params['expand_calendars']) {
                    $result = self::expandCalendar($sitemap, $parent, ($id ? $id : 1), $params, $parent->id);
                }
                break;`
It's OK on HTML view but not in XML view.

**Comment by svanschu** [comment]
Hi, the plugins are on separate repositories, but I redesign the code anyway and dpcalendar would have Ben the next plugin to adapt.

**Comment by svanschu** [comment]
Hi, yes the list is missing currently and the category includes the events the wrong way. I'm on it.

**Comment by svanschu** [comment]
A testable release candidate is available https://extensions.schultschik.com/schuweb-sitemap/pre-release/schuweb-sitemap-5-0-0-rc2

**Comment by AlainRnet** [comment]
Another thing: in my menu I have a link to all DPCalendar events and I would like the Sitemap to display this link and then list all the events on the page.
In the Sitemap, an intermediate link is created that displays a page with the calendar. However, not only do I not need it but I do not use it and this page may be indexed and mislead my visitors as the display is not optimal according to our use.

**Comment by svanschu** [comment]
Hey thank you for testing.

> I note that the index.php link?option=com_schuweb_sitemap&view=xml&tmpl=component&id=1 no longer works, I have to systematically create the sitemap.xml from the administration. 
It makes much more sense to create real xml files than on the fly generation. Since Joomla has since v4 the ability of automation, with 5.1 it is planned to support Joomla Tasks. But I don't wanted to push the v5 release any further to the future.

> OK, but the problem is that the created sitemap contains /administrator/, whose events in the administration will be indexed while it should be those in frontend.
Oh I thought I've got every one. Will check on that


> Furthermore, the URL is not SEF. How can this be corrected? Thanks again!
Damn, I was development blind. I will check on that.

Thank you very much. Another two pairs of eyes is very helpfull.

**Comment by AlainRnet** [comment]
Thank you very much for all your comments. It is a pleasure to help according to my possibilities.
