### ISSUE TITLE
Bug in Jatex 1.5.0

### ISSUE THREAD

**Issue by einue** [svanschu/SchuWeb-Sitemap#109]
**Steps to reproduce**
I updated my joomla site from joomla 3.9.x. to joomla 3.10.12 on my local xampp. I update the jatex extension from 1.2.2 to 1.5.0.

Now, the jatex doesn't work anymore and I get the following error in browser console: 
<img width="1243" alt="image" src="https://github.com/svanschu/SchuWeb-Sitemap/assets/33625116/3885c975-ea8e-44a7-b260-def1b52c514b">
 

**Expected behavior**

**Actual result**

**System information**
Joomla version: 3.10.12
SchuWeb-Sitemap version: 
PHP version: 8.2.4
Database version:

**Comment by svanschu** [comment]
Thank you for report. I will setup a test env with those versions and try to reproduce

**Comment by svanschu** [comment]
Hi @einue I can't reproduce your issue. 

I created fresh Joomla 3.10.12 installation with php 8.2.4 and every thing are default settings.

**Comment by einue** [comment]
@svanschu : I did a freh Joomla installation on my xampp setup too and there is everything fine. Hm, so that's maybe a problem during my update from 3.9.x to 3.10.12? Are there some js-files which I have to remove manually.

**Comment by svanschu** [comment]
Shouldn't be.

I will test a jatex update as well.

Which settings are you using? Any other extension which could interfere?

**Comment by einue** [comment]
Here are the extensions I use
<img width="1173" alt="image" src="https://github.com/svanschu/SchuWeb-Sitemap/assets/33625116/3df6779e-b84c-487b-95be-25e185c3a1c9">
I use template beez3  (or an own template based on beez3).

The php settings:
<img width="519" alt="image" src="https://github.com/svanschu/SchuWeb-Sitemap/assets/33625116/33e72f9a-a4ec-422a-892d-60cf9480cea9">

**Comment by svanschu** [comment]
Hi, is BibTex content plugin active as well? This could interfere perhaps.

**Comment by svanschu** [comment]
Ok I found it. It is because of beez3. Protostar does not have that issue, but with beez3 it appears.

**Comment by einue** [comment]
@svanschu  you're right, using protostar and disabling the bibtex extension works. 
If bibtex is enabled the same error appears.

I testet a little bit with different versions. For protostar and jatex 1.5.0 and bibtex 1.1.5.2 it works. But using bibtex and jatex together on one page causes the error "Uncaught (in promise) TypeError: t.getAttribute is not a function" again.

**Comment by svanschu** [comment]
Bibtex doesn't matter. It is enough to have only clean J3 with Jatex and activating beez3.

What is your bigger plan on that one? Do you plan to go on J4 in the near future?

To fix that either one of both libs would need to use a different prefix.

MathJax is stale in their development, the last version is from 2022, and I plan to add KaTex lib as second option, but only for J4+

**Comment by einue** [comment]
@svanschu  thank you for your support. My plan is to go to J4. Today I could update my J3.10.12 to J4.0.4 on my local machine. The newest jatex and bibtex are now working on one page without errors. :) 

I only have to customize the cassiopeia template.

**Comment by svanschu** [comment]
@einue Good to here, you're welcome. 
I'm always happy, if I can help.
Happy to see that JaTeX is actually used and it is worth to maintain it further.

If you want to support the project, in any kind, you can find the information on the project site https://github.com/svanschu/Joomla-Tex-Tools

Thank you for using JaTeX
