### ISSUE TITLE
Add check robots.txt for access warnings

### ISSUE THREAD

**Issue by 810** [svanschu/SchuWeb-Sitemap#11]
Google give me now warnings for the images because it protected by the robots.txt

**Comment by svanschu** [comment]
which images your talking about?

**Comment by 810** [comment]
blog articles images.

**Comment by svanschu** [comment]
What blog article images? Show me the warning please.

Images which where in the /image/ folder are not protected and anyway doesn't the sitemap images. It's plain text und links.

**Comment by 810** [comment]
![kk](https://cloud.githubusercontent.com/assets/876623/21613131/310c8220-d1d4-11e6-9259-d7142c2ce54f.png)

**Comment by svanschu** [comment]
@810 sorry for the huge delay. Does this error persist? I created me a new Joomla 3.9.16 and Kunena 5.1.16 installation and added the sitemap to the new Google Search Console. 
Currently I can't see such errors in the Search Console

**Comment by 810** [comment]
yes is now successful
