### ISSUE TITLE
URL is not SEF

### ISSUE THREAD

**Issue by svanschu** [svanschu/SchuWeb-Sitemap#113]
Furthermore, the URL is not SEF. How can this be corrected?
Thanks again!

_Originally posted by @AlainRnet in https://github.com/svanschu/SchuWeb-Sitemap/issues/108#issuecomment-1835798701_

**Comment by svanschu** [comment]
@AlainRnet can you give me an example of URL which is not SEF?

As soon as you configure your website to use SEF URLs, the sitemap does this as well.

Small example
```

 <url>
  <loc>http://localhost:43000/schuweb-sitemap-dev-j4/sample-layouts/articles/joomla</loc>
  <lastmod>2022-02-06T23:47:55Z</lastmod>
  <changefreq>weekly</changefreq>
  <priority>0.5</priority>
 </url>
 <url>
  <loc>http://localhost:43000/schuweb-sitemap-dev-j4/typography</loc>
  <lastmod>2022-02-06T23:47:55Z</lastmod>
  <changefreq>weekly</changefreq>
  <priority>0.5</priority>
 </url>
 <url>
  <loc>http://localhost:43000/schuweb-sitemap-dev-j4/calendar</loc>
  <changefreq>weekly</changefreq>
  <priority>0.5</priority>
 </url>
 <url>
  <loc>http://localhost:43000/schuweb-sitemap-dev-j4/calendar&Itemid=210</loc>
  <changefreq>weekly</changefreq>
  <priority>0.5</priority>
 </url>
 <url>
  <loc>http://localhost:43000/schuweb-sitemap-dev-j4/calendar-profile</loc>
  <changefreq>weekly</changefreq>
  <priority>0.5</priority>
 </url>
 <url>
  <loc>http://localhost:43000/schuweb-sitemap-dev-j4/calendar-timeline</loc>
  <changefreq>weekly</changefreq>
  <priority>0.5</priority>
 </url>
```

**Comment by AlainRnet** [comment]
I think it's okay since you settled the removal of administrator in the links. Do you have an installable zip of the plugin I can test?

**Comment by svanschu** [comment]
It is released https://extensions.schultschik.com/schuweb-sitemap/schuweb-sitemap-5-0-0

**Comment by AlainRnet** [comment]
Oh, stupid, I was looking in github. Thank you very much.

**Comment by AlainRnet** [comment]
off-topic question: how do you create the archive from a github src subfolder?

**Comment by svanschu** [comment]
If you make a release, github will put everything in a archive. But this is not controllable.

I use PHING to create my packages, to control the structure and change dates and version numbers with a variable on building the joomla extension package.
