### ISSUE TITLE
XML generation (through tasks or cron)

### ISSUE THREAD

**Issue by Savama51** [svanschu/SchuWeb-Sitemap#120]
Hi,

I was looking for a simple extension that can create an xml sitemap in Joomla 5, Just discovered this extension, looks great !
Unfortunately, I need to automate the xml generation daily...
Is it planned ? Through cron or J5 tasks ?

Thanks !

**Comment by svanschu** [comment]
Hi, yes it is planned for the 5.1 release with J5 task.
Currently working on it.

**Comment by Savama51** [comment]
Good news then, thanks !

**Comment by svanschu** [comment]
@Savama51 https://extensions.schultschik.com/schuweb-sitemap/schuweb-sitemap-5-1-0
