### ISSUE TITLE
Task Scheduler Translations

### ISSUE THREAD

**Issue by Savama51** [svanschu/SchuWeb-Sitemap#124]
Hi,

I have translated latest version 5.1.0 to French.
I can't find how to translate the new feature : task

So, 2 questions:
1. How to translate Task part ?
2. Can you join fr-FR translation ? How to send you ini files ?

**Comment by svanschu** [comment]
Cool!

1. The task language files are located under https://github.com/svanschu/SchuWeb-Sitemap/tree/main/src/plugins/task/schuwebsitemap/language/en-GB
2. If you are familiar with the GitHub workflow, you can fork the repo, make your changes and open a PullRequest for the "next" branch. If not you can attach the files to an issue like this, and I will add them manually

Thank you

**Comment by Savama51** [comment]
My bad, I realized that I translated v5.0.2 files !!
I I'll get back on it very quickly and come back to you :)

**Comment by Savama51** [comment]
Here are the french ini files for 5.1.0.
Up to date !

[schuweb_sitemap_5.1.0_fr-FR.zip](https://github.com/svanschu/SchuWeb-Sitemap/files/14509831/schuweb_sitemap_5.1.0_fr-FR.zip)

**Comment by svanschu** [comment]
Thank you
