### ISSUE TITLE
Weblinks 5.1.0 does not include link status or publishing date (start/finish)

### ISSUE THREAD

**Issue by peterhulst** [svanschu/SchuWeb-Sitemap#131]
**Steps to reproduce**
Make links with status: unpublished or recent date not within the publishing dates (start/finish)

**Expected behavior**
The weblink is **not displayed** in the sitemap when unpublished or  date not in range publishing dates.

**Actual result**
The links is displayed, but clicking on it gives a 404 error.

**System information**
Joomla version: 4.4.3
SchuWeb-Sitemap version: 5.1.0
PHP version: 8.1.27
Database version: 10.6.16-MariaDB-cll-lve

**Comment by peterhulst** [comment]
Hello, 
I have modified weblinks.php version 5.1.0 with the modifications as mentioned above.
It works in my test website.

Regards,
Peter

[weblinks.txt](https://github.com/svanschu/SchuWeb-Sitemap/files/15009871/weblinks.txt)

**Comment by svanschu** [comment]
Hi, thx for using SchuWeb Sitemap, for reporting and proposing a fix.

I will test and add it to the next version.

**Comment by svanschu** [comment]
Thank you. 
The patch was well written and is added to the plugin 
https://github.com/svanschu/SchuWeb-Sitemap-Weblinks/commit/880874a73b120257eacf74e98e576cd47c4499af
