### ISSUE TITLE
Duplicate images

### ISSUE THREAD

**Issue by mediafoks** [svanschu/SchuWeb-Sitemap#133]
If the image of the introductory text and the image of the full text of the material are the same, then they are duplicated in the sitemap for images.

**System information**
Joomla version: 5.1
SchuWeb-Sitemap version:  5.1.0
PHP version: 8.2.17
Database version: 8.0.35

**Comment by svanschu** [comment]
The duplicated images should be removed with this version.

Please text. Thx

[pkg_schuweb_sitemap_5.1.1-133_20240613.zip](https://github.com/user-attachments/files/15829459/pkg_schuweb_sitemap_5.1.1-133_20240613.zip)

**Comment by mediafoks** [comment]
> Дублированные изображения должны быть удалены в этой версии.
> 
> Пожалуйста, напишите. Спасибо
> 
> [pkg_schuweb_sitemap_5.1.1-133_20240613.zip](https://github.com/user-attachments/files/15829459/pkg_schuweb_sitemap_5.1.1-133_20240613.zip)

Yes, everything is great! Thank you!

**Comment by svanschu** [comment]
Merged to next
