### ISSUE TITLE
Can't remove last mod date <lastmod>

### ISSUE THREAD

**Issue by sshcli** [svanschu/SchuWeb-Sitemap#14]
Can't remove last mod date (lastmod)
There's no option to remove the last mod date (lastmod)
According to the sitemap standard, this should be an optional value, not mandatory.

Tested with:
PHP 7.0.13
MySQL 5.6.34
Joomla 3.6.4
SchuWeb-Sitemap 3.0.0.B1

**Comment by svanschu** [comment]
https://www.sitemaps.org/en_GB/protocol.html#sitemapIndex_lastmod

**Comment by sshcli** [comment]
Exactly, I read that link before opening this issue.

**Comment by svanschu** [comment]
Was as note for me, never read a sitemap standard ;)

**Comment by svanschu** [comment]
The commit should fix this, but i think #19 should be fixed before we can test it totally.

**Comment by sshcli** [comment]
OK, I will wait until next release to test all togueter

**Comment by svanschu** [comment]
Save config issue fixed so I can close this here too
