### ISSUE TITLE
PLG_TASK_SCHUWEBSITEMAP isn't overrided

### ISSUE THREAD

**Issue by AlainRnet** [svanschu/SchuWeb-Sitemap#143]
https://github.com/svanschu/SchuWeb-Sitemap/blob/b6ea4c652665c6d9a5c59ea6794c97054f904f49/src/administrator/components/com_schuweb_sitemap/tmpl/sitemaps/default.php#L152C125-L152C148
On sitemaps liste, I can click on New task but it doesn't work because /administrator/index.php?option=com_scheduler&task=task.add&type=PLG_TASK_SCHUWEBSITEMAP task type is invalid.

Even if I create an override with chain PLG_TASK_SCHUWEBSITEMAP and string schuweb.sitemap.update it doesn't work.
The only way is to replace PLG_TASK_SCHUWEBSITEMAP with schuweb.sitemap.update on default.php file

Sorry for my bad english, I hope you understand me.
Best regards.

**Comment by svanschu** [comment]
Hi,
do you have the current version, because this should be fixed. The name of the type was misleading and has nothing to do with the language strings.
see https://github.com/svanschu/SchuWeb-Sitemap/releases/tag/5.1.1

**Comment by AlainRnet** [comment]
Thank you for your answer. Yes, I have it and I reinstall it.
But URL contains always PLG_TASK_SCHUWEBSITEMAP:
![image](https://github.com/user-attachments/assets/1baa0106-db11-438c-9034-f33e49ae0be6)
which is an invalid type:
![image](https://github.com/user-attachments/assets/b7b778a3-6070-426e-9bd4-1a842198ccd0)

**Comment by Savama51** [comment]
Joomla! 5.1.4
SchuWeb Sitemap 5.1.1

I confirm the issue.
In the SchuWeb Sitemap list, if i click on "new task" on a sitemap line, I get the error "invalid task".
The link is "/administrator/index.php?option=com_scheduler&task=task.add&type=PLG_TASK_SCHUWEBSITEMAP", maybe the origin of the problem, bad link here ?

**Comment by svanschu** [comment]
Ok thx, I will look into it.

**Comment by svanschu** [comment]
Your right I forgot to change the type on two spots. Fixed with the above commit. Will get into next version.

Sorry for the inconveniences
