### ISSUE TITLE
PHP Warning:  Declaration of SchuWeb_SitemapXmlDisplayer::printNode

### ISSUE THREAD

**Issue by sshcli** [svanschu/SchuWeb-Sitemap#17]
I found this in my error_log file:

PHP Warning:  Declaration of SchuWeb_SitemapXmlDisplayer::printNode($node) should be compatible with SchuWeb_SitemapDisplayer::printNode(&$node) in /home/example/public_html/components/com_schuweb_sitemap/views/xml/tmpl/default_class.php on line 0

Tested with:
PHP 7.0.13
MySQL 5.6.34
Joomla 3.6.4
SchuWeb-Sitemap 3.0.0.B1

**Comment by svanschu** [comment]
Didn't noticed those. Can you tell me with which PHP Versionen you got those?

**Comment by sshcli** [comment]
7.0.13
Sorry, I forgot to include it the issue.
