### ISSUE TITLE
plg Kunena change url

### ISSUE THREAD

**Issue by 810** [svanschu/SchuWeb-Sitemap#2]
Now:
https://www.site.demo/component/kunena/94-categoryname

change to:
https://www.site.demo/forum/94-categoryname

**Comment by svanschu** [comment]
How should I?

The link get's created with: 

```
$link = 'index.php?option=com_kunena&view=category&catid=' . $cat->id;

$link = 'index.php?option=com_kunena&view=topic&catid=' . $topic->category_id . '&id=' . $topic->id;
```

And this went through `JRoute::_(link)`
