### ISSUE TITLE
PHP Warning:  Illegal string offset 'enabled'

### ISSUE THREAD

**Issue by sshcli** [svanschu/SchuWeb-Sitemap#20]
I found this in my error_log file:

PHP Warning:  Illegal string offset 'enabled' in /home/example/public_html/components/com_schuweb_sitemap/models/sitemap.php on line 137

Tested with:
PHP 7.0.13
MySQL 5.6.34
Joomla 3.6.4
SchuWeb-Sitemap 3.0.0.B1

**Comment by svanschu** [comment]
Can't reproduce this warning.

I load the sitemap at public area and don't get this PHP Warning. I would need more info how to reproduce it.

**Comment by sshcli** [comment]
I only got this warning once, I haven't seen it anymore.
Maybe it was a temporary warning while I was tweaking the component.
I will close this issue, if I get the warning again, i will open a new issue with more details on how to reproduce it.
