### ISSUE TITLE
Can't install Package

### ISSUE THREAD

**Issue by bunnachart** [svanschu/SchuWeb-Sitemap#25]
Warning

JInstaller: :Install: File does not exist /home/xxxxxx/domains/xxxxx.com/public_html/tmp/install_5891390715e56/admin/elements
Component Install: Failed to copy administrator files.

I install beta 3

**Comment by sshcli** [comment]
A previous issue has been already created for this error:
The issue is: https://github.com/svanschu/SchuWeb-Sitemap/issues/22
