### ISSUE TITLE
Unknown package ID, folder, author and date

### ISSUE THREAD

**Issue by sshcli** [svanschu/SchuWeb-Sitemap#27]
<img width="784" alt="unknown" src="https://user-images.githubusercontent.com/12942731/27400340-ca367990-568d-11e7-86be-7ace7ce3cc7a.PNG">

**Comment by svanschu** [comment]
Folder is only displayed for plugins
package ID is generated by joomla and only displayed for non packages

The others should be fixed
[pkg_schuweb_sitemap_3.0.0.B4.1_20170621.zip](https://github.com/svanschu/SchuWeb-Sitemap/files/1092684/pkg_schuweb_sitemap_3.0.0.B4.1_20170621.zip)

**Comment by sshcli** [comment]
Test results = OK✔

<img width="795" alt="ok" src="https://user-images.githubusercontent.com/12942731/27404079-cc72aa8c-569a-11e7-8f8f-fa17404511a5.PNG">
