### ISSUE TITLE
Beta4 - Undefined variable

### ISSUE THREAD

**Issue by ferino75** [svanschu/SchuWeb-Sitemap#28]
Hi,
thanks for beta 4
but, when I create sitemap and go to Tab "Menus" I got error:

Undefined variable: item in C:\UwAmp\www\experts4seo\administrator\components\com_schuweb_sitemap\views\sitemap\tmpl\edit_menues.php on line 33

Joomla 3.7.2 
PHP 7.0.3

**Comment by svanschu** [comment]
I can't reproduce.

I have Joomla 3.7.2 with PHP 7.0.10 without this issue.

Could you post your menu configuration please.

**Comment by ferino75** [comment]
This error appears, when 
error_reporting = E_ALL
is set in php.ini
When I change to 
error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
then is working OK.

**Comment by svanschu** [comment]
I have it to E_ALL all the time. No error visible to me

**Comment by svanschu** [comment]
should be fixed too
