### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by jed-keenan** [svanschu/SchuWeb-Sitemap#31]
On a fresh build site the menu item for the HTML site map is showing 404: http://www.workplacementnetwork.org/sitemap
All of the settings are at default.

**Comment by svanschu** [comment]
Hi thx for the report.

Could you so kind and explain the issue step by step?

Which Joomla version?
You created a sitemap and created than a link to the sitemap or what have you done to get there.

**Comment by lord1957** [comment]
Hello
I start to check my www with joomla 3.9 via Dev Tools web browser Chrom and found error 404  
/components/com_schuweb_sitemap/assets/css/SchuWeb_Sitemap.css SchuWeb_Sitemap.css  
Failed to load resource: the server responded with a status of 404 (Not Found)
can you advise what kind if solution can be?

**Comment by svanschu** [comment]
Hi @lord1957 

It can be the extension itself. It's old code which I started to maintain. So every error or "not so good thing" you  find is welcome as issue. 

Could you please create a new issue. Your 404 is independent to the original.

Thank you

**Comment by svanschu** [comment]
works with 3.2.0-a2
