### ISSUE TITLE
image sitemap blank screen

### ISSUE THREAD

**Issue by imperialo** [svanschu/SchuWeb-Sitemap#32]
Hi,

die normale Sitemap wird hervorragend erstellt und angezeigt, lediglich bei der Image-Sitemap krieg ich eine weiße Seite ohne Angabe von Fehlern. Was könnte das sein, bzw. wie könnte man herausfinden an was es liegt?

Viele Grüße Impi

**Comment by svanschu** [comment]
Wenn es eine Testseite ist, kannst du in den Joomla Einstellungen das Fehlerreporting auf Developement stellen. Davon ist bei einer Live Seite abzuraten, da damit alle Fehlermeldungen von PHP angeschaltet werden, die vl nicht jeder sehen sollte.

Wenn die Testseite auf einem von dir gemanagten Server läuft, kannst du auch in der php config das Fehlerreporting auf EALL stellen.

Wie gesagt alles nur auf einer Testseite zu empfehlen.
