### ISSUE TITLE
Alle Artikel

### ISSUE THREAD

**Issue by CobaJashi** [svanschu/SchuWeb-Sitemap#34]
Hallo :)
wir haben hunderte von Artikeln, allerdings werden nur 38 Angezeigt. Ideen?

Danke im voraus :)

**Comment by svanschu** [comment]
Hi,

dass ist nicht so toll. Hast mir mehr Informationen bitte?

Joomla Version
PHP Version
Link?

**Comment by CobaJashi** [comment]
@svanschu 

Joomla Version 3.8.5
https://computerbutler.de/index.php?option=com_schuweb_sitemap&view=xml&tmpl=component&id=1
PHP 7 (7.0.25-nmm1)

**Comment by CobaJashi** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Hallo :D

der Fehler sitzt immer zwischen dem Stuhl und Monitor. Wir haben schlichtweg keine Menüs ausgewählt :D vielen Dank für deine schnelle Hilfe.
