### ISSUE TITLE
Can't define priority for kunena topics or categories

### ISSUE THREAD

**Issue by sshcli** [svanschu/SchuWeb-Sitemap#36]
Can't define priority for kunena topics or categories
You can change the settings in the backend, but the changes are not reflected in the sitemap.

**Tested with:**
Joomla 3.8.10
Kunena 5.1.3-dev
SchuWeb Sitemap 3.0.0.B4
PHP 7.2.7

**Comment by sshcli** [comment]
That feature works OK in Beta 2
The problem is only in Beta 4

**Comment by svanschu** [comment]
Thank you for the detail. Is it only with Kunena dev version or with every menü item?

**Comment by svanschu** [comment]
I'll tried to reproduce. I'll wait for more info. I don't use the prority feature on my own, so I'm very interrested.

It looks for me like this for every version B2, B3 and B4

<img width="1412" alt="bildschirmfoto 2018-07-19 um 23 28 22" src="https://user-images.githubusercontent.com/806395/42971144-8b115a92-8bab-11e8-9127-07bc49cec3fd.png">

**Comment by svanschu** [comment]
@sshcli any news?

**Comment by sshcli** [comment]
@svanschu after take a look, I found that this is not a bug.

The priority feature is working only for menus (Joomla and Kunena)
We need to add a new option to support also kunena topics and categories.

Such option does not exist right now in the backend.

**Comment by svanschu** [comment]
@sshcli this sounds legit. I now noticed how complex this piece of software is designed. This could be a bigger change of code for a 3.2 or 4.0. I didn't have yet the best overview to name the amount of work, which has to be done.

**Comment by svanschu** [comment]
@sshcli this was a headache ... it showed that the options for prio and changefreq existited, but the global on/off was not used. This should fix the issue

**Comment by sshcli** [comment]
Great. 
Thanks
I will test it tonight or this weekend and leave my comments here

**Comment by svanschu** [comment]
@sshcli Uploaded an alpha package https://github.com/svanschu/SchuWeb-Sitemap/releases/tag/3.2.0-a2

**Comment by sshcli** [comment]
@svanschu I have tested with the alpha package
I can see that all items now has a priority defined, Great!
Just need to add a new entry in menu to define the general priority for all topics

See image below:

<img width="400" alt="new" src="https://user-images.githubusercontent.com/12942731/88669647-2747e280-d0b2-11ea-982f-0b6c828b3546.PNG">

**Comment by svanschu** [comment]
@sshcli the general priority is set by the Kunena Menu. Is this not enough? What would change with another item?

**Comment by sshcli** [comment]
> general priority is set by the Kunena Menu. Is this not enough? 

you know what @svanschu ?
You are right! 
it's enough with that
No need extra changes for now.

Many Thanks, see you around
