### ISSUE TITLE
Update Site not showing notifications in backend

### ISSUE THREAD

**Issue by sshcli** [svanschu/SchuWeb-Sitemap#40]
**To Reproduce**
Install old version of SchuWeb-Sitemap

**Expected behavior**
If I'm using an old version of SchuWeb-Sitemap, I should be able to see notifications in backend for the new version 3.0.0, because it was already released.

**Actual result**
I can't see any update notification in the backend

**System information (please complete the following information)**
Joomla version: 3.9.5
SchuWeb-Sitemap 3.0.0.B4
Kunena version: 5.1.11-DEV
Php version: 7.3.4
Database version: MySQL 5.7.25

**Comment by svanschu** [comment]
Yes indeed, I changed the name and location for update xml and didn't update the old for the last time.
Should be fixed now
