### ISSUE TITLE
Virtuemart

### ISSUE THREAD

**Issue by webolabo** [svanschu/SchuWeb-Sitemap#42]
Hello,
Any way to get categories and products of Virrtuemart in the sitemap please?
Thank you

**Comment by svanschu** [comment]
Hi @webolabo,
yes it would be possible. But the priority is low right now. If more people vote the feature up, it will be done faster.

If you're a little bit familiar with installing plugins by hand, you can take a look into the existing old VM plugin. This is not tested, I don't know if it works out of the box! https://github.com/svanschu/SchuWeb-Sitemap/tree/master/plugins/schuweb_sitemap/com_virtuemart
You're welcome to report any bugs with it.

regards

**Comment by webolabo** [comment]
Hello,
Thank you very much 
I zipped that folder and installed it but it didn't give nothing on the sitemap 
No VM product as it was on Xmap

**Comment by svanschu** [comment]
Need to test it. How fast do you need it? I have some other projects, which have a higher prio right now ...

**Comment by svanschu** [comment]
@webolabo I fixed the plugin to work now. If you want you could test it.
[plg_virtuemart_3.1.0_b1_20190731.zip](https://github.com/svanschu/SchuWeb-Sitemap/files/3454018/plg_virtuemart_3.1.0_b1_20190731.zip)

**Comment by svanschu** [comment]
@webolabo no reply no testing?

**Comment by webolabo** [comment]
Hello
Really sorry for the late 
I lost my password 
I finally tested it and worked as expected just can't deal with the design of lists and levels 
Thank you very much
