### ISSUE TITLE
Store generated sitemap in cache

### ISSUE THREAD

**Issue by Globulopolis** [svanschu/SchuWeb-Sitemap#46]
I've manage a large site (24k+ articles). With every request, a sitemap is created again, but no loaded from cache, which is significantly faster. Can we improve this component to use filesystem cache?

**Comment by svanschu** [comment]
Hi Globulopolis, I appreciate that my extension has some users :blush:

Sure we can improve this, to be an even better sitemap.

**Comment by svanschu** [comment]
@Globulopolis I'm just inspecting the code and saw, that joomla caching is already available. Do you use Joomla caching or is it deactivated?

**Comment by Globulopolis** [comment]
Yes, cache is on.

**Comment by svanschu** [comment]
It is a bigger change it seems. The could is made to create a cache file, but it doesn't create one.

I need to rewrite things for the 4.0 anyway so I move it there. Doesn't make sense to rewrite code now to fix the issue, if I need to rewrite it later again.

Hope that is ok for you

**Comment by degobbis** [comment]
Probably this can help for J3
https://extensions.joomla.org/extension/structure-a-navigation/site-map/sitemap-cache/
