### ISSUE TITLE
error 404 SchuWeb_Sitemap.css

### ISSUE THREAD

**Issue by lord1957** [svanschu/SchuWeb-Sitemap#47]
Hello
I start to check my www with joomla 3.9 via Dev Tools web browser Chrom and found error 404
/components/com_schuweb_sitemap/assets/css/SchuWeb_Sitemap.css SchuWeb_Sitemap.css
Failed to load resource: the server responded with a status of 404 (Not Found)
can you advise what kind if solution can be?

**System information**
Joomla version: 3.9
SchuWeb-Sitemap version: 3.1 
PHP version: 7.3

**Comment by svanschu** [comment]
Hi @lord1957 

It can be the extension itself. It's old code which I started to maintain. So every error or "not so good thing" you find is welcome as issue.

Currently I need to finisch setup my new dev environment on the hardware, then I can look into it.

Thx for reporting

**Comment by lord1957** [comment]
404
Warning
Update: Could not open update site #206 "SchuWeb Sitemap Update Site", URL: https://raw.githubusercontent.com/svanschu/SchuWeb-Sitemap/master/xmap-update.xml

**Comment by svanschu** [comment]
Hi @lord1957 

this is again a different topic. Which version of SchuWeb sitemap you are using? This URL has changed in beta status of the first version.
1. Go to `Extensions` > `Manage` > `Update Sites`
2. Search for SchuWeb
3. If you see more than one entry for SchuWeb_Sitemap hit the button `Rebuild` at the top.
