### ISSUE TITLE
Page is not mobile friendly

### ISSUE THREAD

**Issue by lord1957** [svanschu/SchuWeb-Sitemap#48]
Hello
after presentation to google for index I have report:
Page is not mobile friendly
This page can be difficult to use on a mobile device
Fix the following issue
Clickable elements too close together
https://search.google.com/test/mobile-friendly?id=r8jgwqr_04gnG8AojV0aiw
![sch](https://user-images.githubusercontent.com/39462124/80585271-b560ee00-8a1b-11ea-8510-b95d922e0760.JPG)

**System information**
Joomla version: 3.9
SchuWeb-Sitemap version: 3.1
PHP version: 7.3
Template: protostar

**Comment by svanschu** [comment]
Hi @lord1957,
how to display a nested list is the job of your template. In this case you would need to adjust the base template.
An extension should not load any css, because then your lists would look in each extension and module different, which you don't want to.
