### ISSUE TITLE
PHP Warning:  A non-numeric value encountered

### ISSUE THREAD

**Issue by sshcli** [svanschu/SchuWeb-Sitemap#58]
**Steps to reproduce the issue**
Check the to error_log file located in root directory

**Expected behavior**
No PHP Warnings

**Actual result**
` PHP Warning:  A non-numeric value encountered in /home/username/public_html/components/com_schuweb_sitemap/views/xml/tmpl/default.php on line 27`

**System information (please complete the following information)**
Joomla version: 3.9.22
Kunena version: 5.1.19
SchuWeb Sitemap: 3.1.0
PHP version: 7.4.11
Database version: MySQL 5.7.31

**Comment by svanschu** [comment]
Could you retest with the 3.2.0 please. The non-numeric warning should be fixed in it.

**Comment by sshcli** [comment]
You are right.
Problem solved in 3.2.0
I'm closing this issue right now.
btw, I like your label "wait for response"
