### ISSUE TITLE
Virtuemart plugin Using $this when not in object context

### ISSUE THREAD

**Issue by ghost-pc-83** [svanschu/SchuWeb-Sitemap#60]
Hello,
Sorry for my googlish
Recently when I activate the Virtuemart plugin I get a fatal error Using $ this when not in object context and this for several sites.
Thank you in advance for your support

**System information**
Joomla version: 3.9.23
SchuWeb-Sitemap version: 3.2.0
PHP version: 5.6/7.3/7.4
Database version: 3.9.22-2020-09-16

**Comment by svanschu** [comment]
Hi, thanks for reporting. Could you add which version of vituemart you are using?

**Comment by ghost-pc-83** [comment]
Hi,

Sorry V3.8.6  10373

**Comment by svanschu** [comment]
Ah now I can reproduce it. Thank you, I will look into it.

**Comment by svanschu** [comment]
I made a hotfix for you @ghost-pc-83 . Could you please test?
[plg_virtuemart_3.2.1_b1_20201218.zip](https://github.com/svanschu/SchuWeb-Sitemap/files/5714951/plg_virtuemart_3.2.1_b1_20201218.zip)

**Comment by ghost-pc-83** [comment]
Hi,
I just installed it on 6 websites everything is perfect, I continue to update the others during the day and inform you if I encounter a problem. In any case, thank you for your responsiveness.
Belle journée

Pascal Fabre

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Sven Schultschik<mailto:notifications@github.com>
Envoyé le :vendredi 18 décembre 2020 10:58
À : svanschu/SchuWeb-Sitemap<mailto:SchuWeb-Sitemap@noreply.github.com>
Cc : ghost-pc-83<mailto:p.fabre@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [svanschu/SchuWeb-Sitemap] Virtuemart plugin Using $this when not in object context (#60)


I made a hotfix for you @ghost-pc-83<https://github.com/ghost-pc-83> . Could you please test?
plg_virtuemart_3.2.1_b1_20201218.zip<https://github.com/svanschu/SchuWeb-Sitemap/files/5714951/plg_virtuemart_3.2.1_b1_20201218.zip>
