### ISSUE TITLE
Missing Title in Site map

### ISSUE THREAD

**Issue by tramber91** [svanschu/SchuWeb-Sitemap#63]
Hi

Thanks for your component 
Strange, in first install all run ok,  but
In back, Default values
Component see my menus.
In the single site default site map I use in my menu link, Options, Menu Title is enable, Menu title Yes

But in Front - Site map  Menu link
https://boutique.abbayejouarre.org/plan-du-site
I cannot see the menu title ?

Balise are here  `<h2 class="menutitle"></h2>` , checked with inspector,  but without value.

Balise diseappear when Options, Menu Title is disable, Menu title No

Strange, I said

Take care
Bertrand

**System information**
Joomla version: 3.9.25
SchuWeb-Sitemap version: 3.2.1
PHP version: 7.3.27
Database version: 5.5.30

**Comment by svanschu** [comment]
Hi @tramber91 ,

thank you for using SchuWeb Sitemap.

I try to summarize if I understood the problem right.

If

**Comment by tramber91** [comment]
Hi
Thanks for your quick answer

No, In first install and set, all seems OK out missing title of some menus
So from the beginning

On my example
https://boutique.abbayejouarre.org/plan-du-site
You can see only one Menu title "Menu utilisateur", missing 3 menu titles
Concerning,  "Menu utilisateur", I just discover that, I was focus on first missing menu title

When I said in back, it is administration part of Joomla

**Comment by svanschu** [comment]
@tramber91 could you please test if the issue still exist?
[pkg_schuweb_sitemap_3.3.0-b1_20210422.zip](https://github.com/svanschu/SchuWeb-Sitemap/files/6359774/pkg_schuweb_sitemap_3.3.0-b1_20210422.zip)

**Comment by tramber91** [comment]
Hi  Sven

Thanks, It is OK now with your upgrade
https://boutique.abbayejouarre.org/plan-du-site

no way to play with menu ordering (sequenceing) the new version ?

take care
Bertrand

**Comment by svanschu** [comment]
Hi @tramber91 , 

I know that ordering is an issue. One step after another, don't want to make the release circles as long as in the past. There should be an issue for it, if not, feel free to create one.
