### ISSUE TITLE
error in sitemap §choose§ field

### ISSUE THREAD

**Issue by svanschu** [svanschu/SchuWeb-Sitemap#65]
Support request via E-Mail

When I try to change sitemap in menu" edit item, I get the following error...
An error has occurred.
0 Call to undefined method JoomlaCMSDateDate::toFormat()

**Comment by gitkrasty** [comment]
I have the same issue with latest joomla 3 and latest PHP - when I select 'Choose a site map',   same error pops up.

**Comment by svanschu** [comment]
@gitkrasty Could you please specify latest J3 and PHP? Thank you

**Comment by gitkrasty** [comment]
> @gitkrasty Could you please specify latest J3 and PHP? Thank you

Database Type    mysql
Database Version    5.5.5-10.3.30-MariaDB-1:10.3.30+maria~focal
Database Collation    utf8_general_ci
Database Connection Collation    utf8mb4_general_ci
PHP Version    7.4.22
Web Server    Apache
WebServer to PHP Interface    cgi-fcgi
Joomla! Version    Joomla! 3.9.28 Stable [ Amani ] 6-July-2021 15:00 GMT
Joomla! Platform Version    Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

PHP
Safe Mode    Off
Open basedir    None
Display Errors    Off
Short Open Tags    On
File Uploads    On
Magic Quotes    Off
Register Globals    Off
Output Buffering    Off
Session Save Path    None
Session Auto Start    0
XML Enabled    Yes
Zlib Enabled    Yes
Native ZIP Enabled    Yes
Disabled Functions    disk_total_space, diskfreespace, exec, system, popen, proc_open, proc_nice, shell_exec, passthru, dl
Multibyte String (mbstring) Enabled    Yes
Iconv Available    Yes
Maximum Input Variables    5000

**Comment by svanschu** [comment]
Fixed in 3.3.1
