### ISSUE TITLE
Error 0 XML-Verarbeitungsfehler: nicht wohlgeformt

### ISSUE THREAD

**Issue by ChristianGade** [svanschu/SchuWeb-Sitemap#70]
XML-Sitemap generated

XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: https://www.praxis-johanniskirche.de/index.php?option=com_schuweb_sitemap&view=xml&tmpl=component&id=2
Zeile Nr. 6, Spalte 3:
<!DOCTYPE HTML>
--^

**System information**
Joomla version: 3.9.27
SchuWeb-Sitemap version: 3.3.0 
PHP version: 7.4
Database version:

**Comment by svanschu** [comment]
Oh dass ist natürlich nicht schön.

Welche Plugins sind in der Sitemap aktiv?

**Comment by svanschu** [comment]
Wenn Sie ein Testsystem haben kann ich mir das auch direkt anschauen, wenn sie möchten.
