### ISSUE TITLE
behavior::modal not found.

### ISSUE THREAD

**Issue by micker** [svanschu/SchuWeb-Sitemap#71]
i test your extension on j4 RC4
any admin view display this error
behavior::modal not found.
thanks for any update

**Comment by svanschu** [comment]
Thank you for report. The last test was a while ago with a nightly, so thank you for the hint. I will investigate.

**Comment by svanschu** [comment]
currently working on it

**Comment by svanschu** [comment]
Could you please test with this version?
[pkg_schuweb_sitemap_3.3.2_B1_20210912.zip](https://github.com/svanschu/SchuWeb-Sitemap/files/7148848/pkg_schuweb_sitemap_3.3.2_B1_20210912.zip)

**Comment by svanschu** [comment]
@micker Could you please test with

[pkg_schuweb_sitemap_3.3.2_B2_20210919.zip](https://github.com/svanschu/SchuWeb-Sitemap/files/7192907/pkg_schuweb_sitemap_3.3.2_B2_20210919.zip)

Thank you
