### ISSUE TITLE
500 behavior::tooltip not found

### ISSUE THREAD

**Issue by fontanil** [svanschu/SchuWeb-Sitemap#72]
**Steps to reproduce**
Install and try to edit the default sitemap

**Expected behavior**
Editing page

**Actual result**
500 behavior::tooltip not found

**System information**
Joomla version: 4.0.2
SchuWeb-Sitemap version: 
PHP version: 7.4.20
Database version:

**Comment by fontanil** [comment]
Additionnaly an error 500 when I try to view the maps
`Compile Error: require_once(): Failed opening required '/home/www/sitesclients/jpsounds/components/com_content/helpers/route.php' (include_path='.:/etc/phpnet/php/74/lib/php')`

**Comment by svanschu** [comment]
Thank you for reporting

**Comment by svanschu** [comment]
@fontanil  Could you please test with this version?
[pkg_schuweb_sitemap_3.3.2_B1_20210912.zip](https://github.com/svanschu/SchuWeb-Sitemap/files/7148848/pkg_schuweb_sitemap_3.3.2_B1_20210912.zip)

**Comment by fontanil** [comment]
Hi Sven,
Installation and edition OK.
But for xml, html and images:
`Compile Error: require_once(): Failed opening required '/home/www/site******/*******/components/com_content/helpers/route.php' (include_path='.:/etc/phpnet/php/74/lib/php')`
Error in '/plugins/schuweb_sitemap/com_content/com_content.php (line 10) '

**Comment by svanschu** [comment]
Thx for the fast reply.
Captain Obvious is calling, I shouldn't test in the night. Forgot to activate the content plugin again on my test system.
I'm on it

**Comment by svanschu** [comment]
Hi @fontanil ,
I fixed com_content now. The other plugins I didn't test yet with J4. But I created issues for each of them.
If your using one of those and have issue please use one of the other open issues.

Have fun testing.

[pkg_schuweb_sitemap_3.3.2_B2_20210919.zip](https://github.com/svanschu/SchuWeb-Sitemap/files/7192907/pkg_schuweb_sitemap_3.3.2_B2_20210919.zip)

Thank you!

**Comment by fontanil** [comment]
Thanks Sven, but there is another error: 
ERROR 0 - Call to a member function setName() on null in \libraries\vendor\joomla\database\src\DatabaseQuery.php:1926

**Comment by svanschu** [comment]
Hi @fontanil ,

for this one I would some more details about your setup and settings. For the setting combination I used I fixed all of those setName issues.

Could you give me an inside of your settings of SchuWeb Seitemap and the com_content plugin. Do you use any other sitemap plugin?

**Comment by fontanil** [comment]
The site is on PHP 7.4, Joomla! 4.0.3 (Wampserver 64)
Installation, no option changed, then click on xml, news or images sitemap and the error is displayed.

**Comment by svanschu** [comment]
Yes your right @fontanil 

The project would need more testers like you :)

[pkg_schuweb_sitemap_3.4.0_B3_20210922.zip](https://github.com/svanschu/SchuWeb-Sitemap/files/7206528/pkg_schuweb_sitemap_3.4.0_B3_20210922.zip)

**Comment by fontanil** [comment]
Thanks Sven! :)
It's OK now for XML sitemap. The articles are well listed.
No HTML sitemap link in this new version?
The images sitemp displays only its header, no image link, but I never used it so I don't know if it's correct or not.
The news sitemap displays a database error:
"1064
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '06?? AND `a`.`access`IN (1,4)) AND (`a`.`publish_up`IS NULL OR `a`.`publish...' at line 6 in D:\wamp64\www\bmav4\libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php:141" (JROOT\plugins\schuweb_sitemap\com_content\com_content.php:442 )

**Comment by svanschu** [comment]
@fontanil created to new topics for the other issues.

What you mean with "No HTML sitemap link in this new version?" I didn't remove anything.

**Comment by fontanil** [comment]
![image](https://user-images.githubusercontent.com/8665970/134358884-32e7bdc4-5b54-4988-9476-fddeae22a780.png)

**Comment by svanschu** [comment]
@fontanil I don't get it. In J3 it looks the same.

![grafik](https://user-images.githubusercontent.com/806395/134374709-fe786d6d-9ba3-4a4d-96a1-4278006a2a66.png)

I can't remember of any HTML link in the backend.

**Comment by fontanil** [comment]
Sorry, I'm using OSmap on some sites and it displays a html map, so I confused the two extensions

**Comment by svanschu** [comment]
Soso you're using another sitemap provider 😉
If this is a needed use case for you,  you could create a feature request.
